name = "xnxx"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

[[kv_namespaces]]
binding = "V2RAY"
id = "d3e299aaf6624e76bc4f9bae9dee4377"




[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }


[vars]
#UUID = "0fbf4f81-2598-4b6a-a623-0ead4cb9efa8"
UUID = "0fbf4f81-2598-4b6a-a623-0ead4cb9efa8"
#, "aaaaaa1-bbbb-4ccc-accc-eeeeeeeeeee1", "00000000-0000-0000-0000-000000000000"]
MAIN_PAGE_URL = "https://raw.githubusercontent.com/kcepu877/bot/refs/heads/main/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/kcepu877/bot/refs/heads/main/api.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/kcepu877/bot/refs/heads/main/proxy.html"

[[routes]]
pattern = "cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "zoomcares.zoom.us.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "partner.zoom.us.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "zoomgov.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "gomarketplacecontent-cf.zoom.us.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "investors.fb.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "bimbel.ruangguru.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "edu.ruangguru.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.sea-sw.swiftserve.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "api.blibli.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "unnes.ac.id.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "fikom.esaunggul.ac.id.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "app.gopay.co.id.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "chat.sociomile.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "api.quipper.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.cloudproxy.c-bnn.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.cloudproxy.c-bnn.xyz"
custom_domain = true
